### ISSUE TITLE
Evaluation scripts

### ISSUE THREAD

**Issue by tungdq212** [DXOMARK-Research/PIQ2023#3]
Hello, thank for your work.
Can you public you JOD evaluation code, or a simply method to calculate this scores like your Table 1 in paper?

**Comment by nicolasch96** [comment]
Hello, 

We will be publishing the results very soon!  To calculate the ranked correlation (SROCC),  you need to calculate the average per scene,  and then average the srocc of all scenes.  Please use the official splits (device split and test split) that we shared in this repo.

**Comment by tungdq212** [comment]
@nicolasch96 thank for your quick response.
One more question:

> Two images are 1 JOD apart if 75% of observers choose one as better than the other.

So how to convert JOD into float like in csv? Device by number of comparison?

**Comment by nicolasch96** [comment]
Hello,

The jod is already generated in the csv.  To do so,  you need to use the trueskill implementation presented in this repo: https://github.com/gfxdisp/asap.  If you want to use the full statistical analysis you have to use our algorithm which will also be shared in the near future.

Please do not hesitate to ask other questions that you may have.

Nicolas

**Comment by nicolasch96** [comment]
Please refer to this paper for more clarification about JOD: https://arxiv.org/abs/1712.03686

**Comment by nichahine** [comment]
Excellent question, I again apologize for the delay in publishing SEM-HyperIQA. One solution we have it to only load the pretrained backbone of Resnet50, and then creating the LDA accordingly to the input size. So these layers will NOT be loaded with the pretrained model. Only for 224 patches I suppose since this was the ones used by HyperIQA if I am not wrong. This is unfortunate since we cannot benefit from the whole pretrained HyperIQA model.

**Comment by nichahine** [comment]
We used exactly the same architecture from this repo: https://github.com/SSL92/hyperIQA . We adapted it however to get multiple input sizes. I will try to push faster the code and put it on github ASAP!

**Comment by tungdq212** [comment]
@nicolasch96 Did you modify or remove last Linear layer of LAD?
